apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: temp-team-a
  description: Temp Team A
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: divyanshigupta3295@gmail.com
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: divyanshigupta
spec:
  profile:
    # Intentional no displayName for testing
    email: divyanshigupta3295@gmail.com
  memberOf: [temp-team-a]
---
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: rohitratannagar
  tag: abcd
  description: abcd
spec:
  profile:
    # Intentional no displayName for testing
    email: rohitratannagar2003@gmail.com
  memberOf: [temp-team-a]
---
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: mitesh98
  tag: abcd
  description: abcd
spec:
  profile:
    # Intentional no displayName for testing
    email: iitnmitesh@gmail.com
  memberOf: [temp-team-a]
---
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: its-mitesh-kumar
spec:
  profile:
    # Intentional no displayName for testing
    email: itsmiteshkumar98@gmail.com
  memberOf: [temp-team-a,temp-team-b]
---
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: mitesh-kumar
spec:
  profile:
    # Intentional no displayName for testing
    email: miteshatcusat@gmail.com
  memberOf: [temp-team-a]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nationalparks-py
  labels: 
    component: nationalparks-py
  annotations:
    github.com/project-slug: divyanshiGupta/nationalparks-py
    backstage.io/kubernetes-id: nationalparks-py
    tekton.dev/cicd: "true"
    jfrog-artifactory/image-name: hello-world
    azure-container-registry/repository-name: hello-world
    backstage.io/techdocs-ref: dir:.
    # backstage.io/kubernetes-namespace: div
spec:
  type: service
  lifecycle: unknown
  owner: temp-team-a
