apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: development
  description: development team
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: development@gmail.com
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: rohitratannagar
spec:
  profile:
    # Intentional no displayName for testing
    email: rohitratannagar2003@gmail.com
  memberOf: [development, Agent, group:default/red-hat]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: rrn-bit
spec:
  profile:
    # Intentional no displayName for testing
    email: rrn7037@gmail.com
  memberOf: [development]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Agent
  description: Agent team
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: agent@gmail.com
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: its-mitesh-kumar
spec:
  profile:
    # Intentional no displayName for testing
    email: miteshkumar@gmail.com
  memberOf: [development]
